#!/bin/bash
echo "=> Building Rodan"
docker build --build-arg BRANCHES=develop --tag d33pi0/docker-hooks:nightly .
docker build --build-arg BRANCHES=develop --tag d33pi0/second:nightly ./someplace_else
